### ISSUE TITLE
Wrong BEM usage: no 'content' block

### ISSUE THREAD

**Issue by rudnitskih** [MasterLuiji19/sports-app-landing#13]
I see 'content' elements, but don't see such block itself

![image](https://user-images.githubusercontent.com/8848858/56497957-5d3e0480-6508-11e9-990c-0de0bb1dc9c4.png)

**Comment by rudnitskih** [comment]
Та же проблема с элементами вот здесь

<img width="940" alt="Screen Shot 2019-04-22 at 14 11 18" src="https://user-images.githubusercontent.com/8848858/56497991-85c5fe80-6508-11e9-90bd-794b5312e0d2.png">

**Comment by MasterLuiji19** [comment]
request: Please indicate line numbers where errors are.. Thank's!)

**Comment by rudnitskih** [comment]
типо все места где проблемы?

ну тут идея такая - если есть элемент `social__list-item` - где то должен быть элемент с классом `social`. Если его нет, значит это элементы не того блока.

**Comment by MasterLuiji19** [comment]
да, я понял. просто не сразу нашел где это)
