### ISSUE TITLE
Move slick out of source folder

### ISSUE THREAD

**Issue by rudnitskih** [MasterLuiji19/sports-app-landing#15]
<img width="1073" alt="Screen Shot 2019-04-22 at 14 13 33" src="https://user-images.githubusercontent.com/8848858/56498064-d4739880-6508-11e9-874e-7f907248ce1c.png">

**Comment by MasterLuiji19** [comment]
move to the level with the folder "src"?

**Comment by rudnitskih** [comment]
create `lib` folder near the `src` and put into it

**Comment by MasterLuiji19** [comment]
oky doky)
